# Generated by Django 4.1.5 on 2023-02-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefecture", models.CharField(max_length=10)),
                ("weather", models.CharField(max_length=10)),
            ],
        ),
    ]
