# Generated by Django 4.1.5 on 2023-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weather",
            options={
                "verbose_name": "WeatherInfo",
                "verbose_name_plural": "WeatherInfo",
            },
        ),
        migrations.AddField(
            model_name="weather",
            name="temperature",
            field=models.IntegerField(null=True),
        ),
    ]
